// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using modelBindingExampleMvc.Models.Context;

namespace modelBindingExampleMvc.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20220526122111_DbCreated")]
    partial class DbCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("modelBindingExampleMvc.Models.Entities.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("sname")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.HasKey("id");

                    b.ToTable("tblStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
